import type {
  DashboardStats,
  ContinueReadingItem,
  LibraryEntry,
  RecommendedBook,
  Genre,
  DiscoverBook,
} from "./types";

export const mockStats: DashboardStats = {
  pagesToday: 47,
  wordsLearnedThisWeek: 128,
  streakDays: 12,
  timeReadMinutes: 204,
};

export const mockContinueReading: ContinueReadingItem[] = [
  {
    openitiId: "0723IbnAjurrum.Ajrumiyya",
    titleAr: "الأجرومية",
    titleLat: "Al-Ajrumiyyah",
    authorName: "Ibn Ajurrum",
    genre: "Nahw",
    level: "Beginner",
    progressPercent: 42,
    lastOpenedAt: "2026-06-03T08:15:00Z",
  },
  {
    openitiId: "0676Nawawi.ArbainNawawiyya",
    titleAr: "الأربعون النووية",
    titleLat: "Al-Arba'in al-Nawawiyyah",
    authorName: "Imam Nawawi",
    genre: "Hadith",
    progressPercent: 67,
    lastOpenedAt: "2026-06-02T21:30:00Z",
  },
  {
    openitiId: "0179MalikIbnAnas.Muwatta",
    titleAr: "الموطأ",
    titleLat: "Al-Muwatta",
    authorName: "Imam Malik",
    genre: "Hadith",
    progressPercent: 18,
    lastOpenedAt: "2026-06-01T14:45:00Z",
  },
];

export const mockLibrary: LibraryEntry[] = [
  // in_progress
  {
    openitiId: "0723IbnAjurrum.Ajrumiyya",
    titleAr: "الأجرومية",
    titleLat: "Al-Ajrumiyyah",
    authorName: "Ibn Ajurrum",
    status: "in_progress",
    progressPercent: 42,
    lastOpenedAt: "2026-06-03T08:15:00Z",
    genre: "Nahw",
    level: "Beginner",
  },
  {
    openitiId: "0676Nawawi.ArbainNawawiyya",
    titleAr: "الأربعون النووية",
    titleLat: "Al-Arba'in al-Nawawiyyah",
    authorName: "Imam Nawawi",
    status: "in_progress",
    progressPercent: 67,
    lastOpenedAt: "2026-06-02T21:30:00Z",
    genre: "Hadith",
  },
  {
    openitiId: "0179MalikIbnAnas.Muwatta",
    titleAr: "الموطأ",
    titleLat: "Al-Muwatta",
    authorName: "Imam Malik",
    status: "in_progress",
    progressPercent: 18,
    lastOpenedAt: "2026-06-01T14:45:00Z",
    genre: "Hadith",
  },
  {
    openitiId: "0676Nawawi.RiyadSalihin",
    titleAr: "رياض الصالحين",
    titleLat: "Riyad al-Salihin",
    authorName: "Imam Nawawi",
    status: "in_progress",
    progressPercent: 31,
    lastOpenedAt: "2026-05-30T10:00:00Z",
    genre: "Hadith",
  },
  {
    openitiId: "0852IbnHajar.BulughMaram",
    titleAr: "بلوغ المرام",
    titleLat: "Bulugh al-Maram",
    authorName: "Ibn Hajar",
    status: "in_progress",
    progressPercent: 8,
    lastOpenedAt: "2026-05-28T16:20:00Z",
    genre: "Hadith",
  },
  // saved
  {
    openitiId: "0256Bukhari.Sahih",
    titleAr: "صحيح البخاري",
    titleLat: "Sahih al-Bukhari",
    authorName: "Imam al-Bukhari",
    status: "saved",
    progressPercent: 0,
    lastOpenedAt: "2026-05-20T09:00:00Z",
    genre: "Hadith",
  },
  {
    openitiId: "0751IbnQayyim.ZadMaad",
    titleAr: "زاد المعاد",
    titleLat: "Zad al-Ma'ad",
    authorName: "Ibn al-Qayyim",
    status: "saved",
    progressPercent: 0,
    lastOpenedAt: "2026-05-15T12:00:00Z",
    genre: "Sirah",
  },
  {
    openitiId: "0728IbnTaymiyya.AqeedaWasitiyya",
    titleAr: "العقيدة الواسطية",
    titleLat: "Al-Aqeedah al-Wasitiyyah",
    authorName: "Ibn Taymiyyah",
    status: "saved",
    progressPercent: 0,
    lastOpenedAt: "2026-05-10T18:30:00Z",
    genre: "Aqeedah",
  },
  {
    openitiId: "0620IbnQudama.UmdatAhkam",
    titleAr: "عمدة الأحكام",
    titleLat: "Umdat al-Ahkam",
    authorName: "Al-Maqdisi",
    status: "saved",
    progressPercent: 0,
    lastOpenedAt: "2026-05-05T08:00:00Z",
    genre: "Fiqh",
  },
  // completed
  {
    openitiId: "1376Mubarakpuri.RahiqMakhtum",
    titleAr: "الرحيق المختوم",
    titleLat: "Al-Rahiq al-Makhtum",
    authorName: "Mubarakpuri",
    status: "completed",
    progressPercent: 100,
    lastOpenedAt: "2026-04-20T20:00:00Z",
    genre: "Sirah",
  },
  {
    openitiId: "0620IbnQudama.LumcatIctiqad",
    titleAr: "لمعة الاعتقاد",
    titleLat: "Lum'at al-I'tiqad",
    authorName: "Ibn Qudamah",
    status: "completed",
    progressPercent: 100,
    lastOpenedAt: "2026-03-15T11:00:00Z",
    genre: "Aqeedah",
  },
  {
    openitiId: "0774IbnKathir.TafsirQuran",
    titleAr: "تفسير ابن كثير",
    titleLat: "Tafsir Ibn Kathir",
    authorName: "Ibn Kathir",
    status: "completed",
    progressPercent: 100,
    lastOpenedAt: "2026-02-10T09:30:00Z",
    genre: "Tafseer",
  },
];

export const mockRecommended: RecommendedBook[] = [
  {
    openitiId: "0256Bukhari.Sahih",
    titleAr: "صحيح البخاري",
    titleLat: "Sahih al-Bukhari",
    authorName: "Imam al-Bukhari",
    genre: "Hadith",
  },
  {
    openitiId: "1376Sadi.TafsirSadi",
    titleAr: "تفسير السعدي",
    titleLat: "Tafsir al-Sa'di",
    authorName: "Al-Sa'di",
    genre: "Tafseer",
  },
  {
    openitiId: "0751IbnQayyim.ZadMaad",
    titleAr: "زاد المعاد",
    titleLat: "Zad al-Ma'ad",
    authorName: "Ibn al-Qayyim",
    genre: "Sirah",
  },
  {
    openitiId: "1376Mubarakpuri.RahiqMakhtum",
    titleAr: "الرحيق المختوم",
    titleLat: "Al-Rahiq al-Makhtum",
    authorName: "Mubarakpuri",
    genre: "Sirah",
  },
  {
    openitiId: "0728IbnTaymiyya.AqeedaWasitiyya",
    titleAr: "العقيدة الواسطية",
    titleLat: "Al-Aqeedah al-Wasitiyyah",
    authorName: "Ibn Taymiyyah",
    genre: "Aqeedah",
  },
  {
    openitiId: "0620IbnQudama.MukhtasarMinhaj",
    titleAr: "مختصر منهاج القاصدين",
    titleLat: "Mukhtasar Minhaj al-Qasidin",
    authorName: "Ibn Qudamah",
    genre: "Tazkiyah",
  },
  {
    openitiId: "0620IbnQudama.UmdatAhkam",
    titleAr: "عمدة الأحكام",
    titleLat: "Umdat al-Ahkam",
    authorName: "Al-Maqdisi",
    genre: "Fiqh",
  },
  {
    openitiId: "0774IbnKathir.TafsirQuran",
    titleAr: "تفسير ابن كثير",
    titleLat: "Tafsir Ibn Kathir",
    authorName: "Ibn Kathir",
    genre: "Tafseer",
  },
  {
    openitiId: "0852IbnHajar.FathBari",
    titleAr: "فتح الباري",
    titleLat: "Fath al-Bari",
    authorName: "Ibn Hajar",
    genre: "Hadith",
  },
  {
    openitiId: "0620IbnQudama.LumcatIctiqad",
    titleAr: "لمعة الاعتقاد",
    titleLat: "Lum'at al-I'tiqad",
    authorName: "Ibn Qudamah",
    genre: "Aqeedah",
  },
];

export const mockGenres: Genre[] = [
  { slug: "nahw", label: "Nahw", count: 1240 },
  { slug: "sarf", label: "Sarf", count: 840 },
  { slug: "hadith", label: "Hadith", count: 1100 },
  { slug: "fiqh", label: "Fiqh", count: 2300 },
  { slug: "tafseer", label: "Tafseer", count: 890 },
  { slug: "aqeedah", label: "Aqeedah", count: 560 },
  { slug: "balagha", label: "Balagha", count: 320 },
  { slug: "lugha", label: "Lugha", count: 610 },
  { slug: "sirah", label: "Sirah", count: 280 },
];

export const mockDiscover: DiscoverBook[] = [
  // Nahw (~20)
  {
    openitiId: "0723IbnAjurrum.Ajrumiyya",
    titleAr: "الأجرومية",
    titleLat: "Al-Ajrumiyyah",
    authorName: "Ibn Ajurrum",
    genre: "Nahw",
    level: "Beginner",
    popularity: 95,
  },
  {
    openitiId: "0761IbnHisham.QatrNada",
    titleAr: "قطر الندى",
    titleLat: "Qatr al-Nada",
    authorName: "Ibn Hisham",
    genre: "Nahw",
    level: "Intermediate",
    popularity: 82,
  },
  {
    openitiId: "0672IbnMalik.AlfiyyaIbnMalik",
    titleAr: "ألفية ابن مالك",
    titleLat: "Alfiyyat Ibn Malik",
    authorName: "Ibn Malik",
    genre: "Nahw",
    level: "Advanced",
    popularity: 90,
  },
  {
    openitiId: "0911Suyuti.BahjaMardiyya",
    titleAr: "البهجة المرضية",
    titleLat: "Bahjat al-Mardiyyah",
    authorName: "Al-Suyuti",
    genre: "Nahw",
    level: "Advanced",
    popularity: 68,
  },
  {
    openitiId: "0769IbnAqil.SharhIbnAqil",
    titleAr: "شرح ابن عقيل",
    titleLat: "Sharh Ibn Aqil",
    authorName: "Ibn Aqil",
    genre: "Nahw",
    level: "Advanced",
    popularity: 78,
  },
  {
    openitiId: "0761IbnHisham.MughniLabib",
    titleAr: "مغني اللبيب",
    titleLat: "Mughni al-Labib",
    authorName: "Ibn Hisham",
    genre: "Nahw",
    level: "Advanced",
    popularity: 72,
  },
  {
    openitiId: "0905Azhari.Tasrih",
    titleAr: "التصريح",
    titleLat: "Al-Tasrih",
    authorName: "Al-Azhari",
    genre: "Nahw",
    level: "Advanced",
    popularity: 55,
  },
  {
    openitiId: "0761IbnHisham.AwdahMasalik",
    titleAr: "أوضح المسالك",
    titleLat: "Awdah al-Masalik",
    authorName: "Ibn Hisham",
    genre: "Nahw",
    level: "Intermediate",
    popularity: 70,
  },
  {
    openitiId: "0761IbnHisham.ShudhurDhahab",
    titleAr: "شذور الذهب",
    titleLat: "Shudhur al-Dhahab",
    authorName: "Ibn Hisham",
    genre: "Nahw",
    level: "Intermediate",
    popularity: 65,
  },
  {
    openitiId: "1101Damanhuri.TuhfaSaniyya",
    titleAr: "التحفة السنية",
    titleLat: "Al-Tuhfa al-Saniyya",
    authorName: "Al-Damanhuri",
    genre: "Nahw",
    level: "Beginner",
    popularity: 60,
  },
  {
    openitiId: "1421IbnUthaymeen.SharhAjrumiyya",
    titleAr: "شرح الأجرومية",
    titleLat: "Sharh al-Ajrumiyyah",
    authorName: "Ibn Uthaymeen",
    genre: "Nahw",
    level: "Beginner",
    popularity: 88,
  },
  {
    openitiId: "0646IbnHajib.Kafiya",
    titleAr: "الكافية",
    titleLat: "Al-Kafiyah",
    authorName: "Ibn al-Hajib",
    genre: "Nahw",
    level: "Advanced",
    popularity: 58,
  },
  {
    openitiId: "0905Azhari.MuqaddimahAzhariyya",
    titleAr: "المقدمة الأزهرية",
    titleLat: "Al-Muqaddimah al-Azhariyyah",
    authorName: "Khalid al-Azhari",
    genre: "Nahw",
    level: "Beginner",
    popularity: 50,
  },
  {
    openitiId: "0957Raini.MutammimahAjrumiyya",
    titleAr: "متممة الأجرومية",
    titleLat: "Mutammimah al-Ajrumiyyah",
    authorName: "Al-Raini",
    genre: "Nahw",
    level: "Intermediate",
    popularity: 45,
  },
  {
    openitiId: "0538Zamakhshari.Mufassal",
    titleAr: "المفصل",
    titleLat: "Al-Mufassal",
    authorName: "Al-Zamakhshari",
    genre: "Nahw",
    level: "Advanced",
    popularity: 48,
  },
  {
    openitiId: "0471Jurjani.AwamilMia",
    titleAr: "العوامل المئة",
    titleLat: "Al-Awamil al-Mi'ah",
    authorName: "Al-Jurjani",
    genre: "Nahw",
    level: "Beginner",
    popularity: 42,
  },
  {
    openitiId: "0516Hariri.MulhatIrab",
    titleAr: "ملحة الإعراب",
    titleLat: "Mulhat al-I'rab",
    authorName: "Al-Hariri",
    genre: "Nahw",
    level: "Beginner",
    popularity: 40,
  },
  {
    openitiId: "0686Radi.SharhKafiya",
    titleAr: "شرح الكافية",
    titleLat: "Sharh al-Kafiyah",
    authorName: "Al-Radi",
    genre: "Nahw",
    level: "Advanced",
    popularity: 52,
  },
  {
    openitiId: "0599Imriti.NazmAjrumiyya",
    titleAr: "نظم الأجرومية",
    titleLat: "Nazm al-Ajrumiyyah",
    authorName: "Al-Imriti",
    genre: "Nahw",
    level: "Beginner",
    popularity: 75,
  },
  {
    openitiId: "1440Tayyar.IrabMuyassar",
    titleAr: "الإعراب الميسر",
    titleLat: "Al-I'rab al-Muyassar",
    authorName: "Al-Tayyar",
    genre: "Nahw",
    level: "Beginner",
    popularity: 35,
  },
  // Hadith
  {
    openitiId: "0256Bukhari.Sahih",
    titleAr: "صحيح البخاري",
    titleLat: "Sahih al-Bukhari",
    authorName: "Imam al-Bukhari",
    genre: "Hadith",
    level: "Advanced",
    popularity: 100,
  },
  {
    openitiId: "0261Muslim.Sahih",
    titleAr: "صحيح مسلم",
    titleLat: "Sahih Muslim",
    authorName: "Imam Muslim",
    genre: "Hadith",
    level: "Advanced",
    popularity: 98,
  },
  {
    openitiId: "0676Nawawi.RiyadSalihin",
    titleAr: "رياض الصالحين",
    titleLat: "Riyad al-Salihin",
    authorName: "Imam Nawawi",
    genre: "Hadith",
    level: "Beginner",
    popularity: 87,
  },
  // Fiqh
  {
    openitiId: "0620IbnQudama.UmdatAhkam",
    titleAr: "عمدة الأحكام",
    titleLat: "Umdat al-Ahkam",
    authorName: "Al-Maqdisi",
    genre: "Fiqh",
    level: "Beginner",
    popularity: 80,
  },
  {
    openitiId: "0595IbnRushd.BidayatMujtahid",
    titleAr: "بداية المجتهد",
    titleLat: "Bidayat al-Mujtahid",
    authorName: "Ibn Rushd",
    genre: "Fiqh",
    level: "Advanced",
    popularity: 74,
  },
  // Tafseer
  {
    openitiId: "0774IbnKathir.TafsirQuran",
    titleAr: "تفسير ابن كثير",
    titleLat: "Tafsir Ibn Kathir",
    authorName: "Ibn Kathir",
    genre: "Tafseer",
    level: "Intermediate",
    popularity: 93,
  },
  {
    openitiId: "1376Sadi.TafsirSadi",
    titleAr: "تفسير السعدي",
    titleLat: "Tafsir al-Sa'di",
    authorName: "Al-Sa'di",
    genre: "Tafseer",
    level: "Beginner",
    popularity: 85,
  },
];
