#!/usr/bin/env bash
#
# sync-env.sh - Syncs env vars from root .env to each sub-project
#
# Usage: ./scripts/sync-env.sh [--push-supabase]
#
# Reads /.env (single source of truth) and writes the relevant
# subset into each project's local env file. Optionally pushes
# secrets to Supabase Vault via the CLI.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found"
  echo "Create it with the required variables (see .env.example)"
  exit 1
fi

# Load all vars from root .env (skip comments and blank lines)
set -a
while IFS='=' read -r key val || [ -n "$key" ]; do
  # Skip comments and empty lines
  [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
  # Strip leading/trailing whitespace from key
  key="$(echo "$key" | xargs)"
  # Remove surrounding quotes from value
  val="${val#\"}"
  val="${val%\"}"
  val="${val#\'}"
  val="${val%\'}"
  export "$key=$val"
done < "$ENV_FILE"
set +a

# --- Helper ---
write_env() {
  local target="$1"
  shift
  local vars=("$@")
  local dir
  dir="$(dirname "$target")"

  mkdir -p "$dir"

  {
    echo "# Auto-generated by sync-env.sh — do not edit manually"
    echo "# Source: .env (project root)"
    echo "# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo ""
    for var in "${vars[@]}"; do
      val="${!var:-}"
      if [ -n "$val" ]; then
        echo "${var}=${val}"
      else
        echo "# ${var}= (not set in root .env)"
      fi
    done
  } > "$target"

  echo "  Wrote $target (${#vars[@]} vars)"
}

echo "Syncing env vars from $ENV_FILE"
echo ""

# --- web/ (Next.js) ---
echo "[web] Next.js waitlist site"
write_env "$ROOT/web/.env.local" \
  SUPABASE_URL \
  SUPABASE_SERVICE_ROLE_KEY \
  RESEND_API_KEY \
  NEXT_PUBLIC_URL \
  EMAIL_FROM

# --- recitation/ (Python) ---
# Check if it uses env vars (currently it doesn't, but future-proof)
if [ -n "${SUPABASE_URL:-}" ]; then
  echo "[recitation] Python recitation server"
  write_env "$ROOT/recitation/.env" \
    SUPABASE_URL \
    SUPABASE_SERVICE_ROLE_KEY
fi

# --- reader/ (if it needs env vars in the future) ---
if [ -d "$ROOT/reader" ]; then
  echo "[reader] Skipped (no env vars needed yet)"
fi

echo ""

# --- Supabase secrets (optional) ---
if [ "${1:-}" = "--push-supabase" ]; then
  echo "[supabase] Pushing secrets to Supabase Vault..."

  if ! command -v supabase &>/dev/null; then
    echo "  Error: supabase CLI not found"
    exit 1
  fi

  # Push relevant secrets
  declare -A secrets=(
    [RESEND_API_KEY]="${RESEND_API_KEY:-}"
    [EMAIL_FROM]="${EMAIL_FROM:-}"
    [NEXT_PUBLIC_URL]="${NEXT_PUBLIC_URL:-}"
  )

  for key in "${!secrets[@]}"; do
    val="${secrets[$key]}"
    if [ -n "$val" ]; then
      echo "$val" | supabase secrets set "$key" --project-ref vcekcwhcvownsdvzmcdd 2>/dev/null \
        && echo "  Set $key" \
        || echo "  Failed to set $key"
    fi
  done

  echo ""
fi

echo "Done. Restart dev servers to pick up changes."
